# Generated by Django 3.1.2 on 2020-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_auto_20201018_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
