# Generated by Django 3.1.2 on 2020-10-21 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0011_auto_20201021_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
